package main

import "net/http"

func (s *Server) serveHTML(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(200)
	_, _ = w.Write([]byte(uiHTML))
}

const uiHTML = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pocketful</title><style>
:root{--ink:#17243a;--muted:#657187;--paper:#f4f7f6;--card:#fff;--accent:#176b5b;--accent2:#dff2eb;--danger:#a63446;--line:#dce4e2;--shadow:0 14px 38px #163c3320}*{box-sizing:border-box}body{margin:0;background:linear-gradient(145deg,#eef5f1,#f8f5ee);color:var(--ink);font:15px/1.5 ui-sans-serif,system-ui,-apple-system,sans-serif;min-height:100vh}header{background:#123f38;color:#fff;padding:18px max(20px,calc((100% - 1120px)/2));display:flex;align-items:center;gap:24px;flex-wrap:wrap}header strong{font:700 24px Georgia,serif;letter-spacing:.4px}nav{display:flex;gap:6px;flex:1}nav a{color:#d9eee8;text-decoration:none;padding:8px 10px;border-radius:9px}nav a:hover,nav a:focus{background:#ffffff18}.identity{display:flex;gap:10px;align-items:center}.identity button{background:transparent;color:white;border-color:#ffffff55}main{max-width:1120px;margin:32px auto;padding:0 20px}.grid{display:grid;grid-template-columns:1.1fr .9fr;gap:22px}.stack{display:grid;gap:18px}.card{background:var(--card);border:1px solid #ffffff;border-radius:20px;padding:22px;box-shadow:var(--shadow)}h1,h2{font-family:Georgia,serif;margin:0 0 16px}h1{font-size:32px}h2{font-size:21px}.eyebrow{text-transform:uppercase;letter-spacing:.12em;font-size:11px;color:var(--muted);font-weight:750}.money{font:700 38px Georgia,serif;color:var(--accent);margin:4px 0}.secondary-money{display:flex;gap:18px;color:var(--muted)}form{display:grid;gap:12px}label{font-weight:650}input,select,button{font:inherit;border:1px solid #bbc9c6;border-radius:11px;padding:11px 12px;width:100%;background:#fff;color:var(--ink)}input:focus,select:focus,button:focus{outline:3px solid #75bfae88;outline-offset:2px}button{cursor:pointer;background:var(--accent);border-color:var(--accent);color:#fff;font-weight:720}button.secondary{background:#fff;color:var(--accent)}button.danger{background:#fff;color:var(--danger);border-color:#d8a4ad}.actions{display:flex;gap:8px}.actions button{width:auto}.error,.uncertain{padding:10px 12px;border-radius:10px;color:var(--danger);background:#fff0f1}.uncertain{color:#765a08;background:#fff7d8}.item{padding:15px 0;border-top:1px solid var(--line)}.item:first-child{border-top:0}.row{display:flex;justify-content:space-between;gap:14px;align-items:start}.pill{font-size:12px;padding:3px 8px;border-radius:999px;background:var(--accent2);color:var(--accent)}.muted{color:var(--muted)}.hidden{display:none!important}.auth{max-width:480px;margin:60px auto}.empty{color:var(--muted);padding:18px 0}.spinner{color:var(--muted)}@media(max-width:700px){header{gap:10px}nav{order:3;overflow:auto;width:100%}main{margin:20px auto;padding:0 14px}.grid{grid-template-columns:1fr}.card{padding:18px;border-radius:16px}.money{font-size:32px}.identity{margin-left:auto}.identity [data-testid=current-user]{display:none}.secondary-money{flex-direction:column;gap:4px}.actions{flex-wrap:wrap}}
</style></head><body><header><strong>Pocketful</strong><nav><a href="/">Wallet</a><a href="/requests">Requests</a><a href="/split">Split</a><a href="/authorizations">Authorisations</a></nav><div class="identity hidden" id="identity"><span data-testid="current-user"></span><span>@<b data-testid="current-handle"></b></span><button data-testid="logout-button" class="secondary" style="width:auto">Log out</button></div></header><main id="app"><p class="spinner">Loading your wallet…</p></main><script>
const $=(s,r=document)=>r.querySelector(s)||(s.startsWith('#')?r.querySelector('[data-testid="'+s.slice(1)+'"]'):null), app=$('#app'), token=()=>localStorage.pocketfulToken||'', headers=(extra={})=>({...extra,...(token()?{Authorization:'Bearer '+token()}:{})});let me=null,refreshVersion=0;
async function api(path,options={}){const r=await fetch(path,{...options,headers:headers({'Content-Type':'application/json',...(options.headers||{})})});let data=null;try{data=await r.json()}catch{}if(!r.ok){let e=new Error(data?.error?.message||'Request refused');e.code=data?.error?.code;e.status=r.status;throw e}return data}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
function fmt(n){let p=me.minor_units;if(!p)return n+' '+me.currency;let v=String(n).padStart(p+1,'0');return v.slice(0,-p)+'.'+v.slice(-p)+' '+me.currency}
function minor(v){if(!/^\d+(\.\d+)?$/.test(v))throw Error('Enter a valid decimal amount');let [a,b='']=v.split('.'),p=me.minor_units;if(b.length>p)throw Error('Too many decimal places');let n=Number(a)*10**p+Number((b+'0'.repeat(p)).slice(0,p));if(!Number.isSafeInteger(n)||n<1)throw Error('Amount must be positive');return n}
function field(id,label,type='text',value=''){return '<label>'+label+'<input data-testid="'+id+'" type="'+type+'" value="'+value+'"'+(id.endsWith('-note')?'':' required')+'></label>'}
function errorBox(id,msg){return msg?'<div class="error" data-testid="'+id+'">'+esc(msg)+'</div>':''}function esc(x){let d=document.createElement('div');d.textContent=x??'';return d.innerHTML}
function showIdentity(){if(!me)return;$('#identity').classList.remove('hidden');$('[data-testid=current-user]').textContent=me.display_name;$('[data-testid=current-handle]').textContent=me.handle}
async function boot(){let path=location.pathname;if(path=='/login'||path=='/signup'){renderAuth(path);$('#identity').remove();return}if(!token()){location.href='/login';return}try{me=await api('/me');showIdentity();route()}catch{localStorage.removeItem('pocketfulToken');location.href='/login'}}
function renderAuth(path){$('#identity').classList.add('hidden');let signup=path=='/signup';app.innerHTML='<section class="card auth"><p class="eyebrow">Secure wallet access</p><h1>'+(signup?'Create your wallet':'Welcome back')+'</h1><form id="auth-form">'+field(signup?'signup-email':'login-email','Email','email')+field(signup?'signup-password':'login-password','Password','password')+(signup?field('signup-display-name','Display name'):'')+'<button data-testid="'+(signup?'signup-submit':'login-submit')+'">'+(signup?'Sign up':'Log in')+'</button><div id="auth-msg"></div></form><p class="muted">'+(signup?'Already registered? <a href="/login">Log in</a>':'New here? <a href="/signup">Create an account</a>')+'</p></section>';$('#auth-form').onsubmit=async e=>{e.preventDefault();let body={email:$('[data-testid='+(signup?'signup-email':'login-email')+']').value,password:$('[data-testid='+(signup?'signup-password':'login-password')+']').value};if(signup)body.display_name=$('[data-testid=signup-display-name]').value;try{let x=await api('/auth/'+(signup?'signup':'login'),{method:'POST',body:JSON.stringify(body)});localStorage.pocketfulToken=x.token;location.href='/'}catch(err){$('#auth-msg').innerHTML=errorBox('auth-error',err.message)}}}
function route(){if(location.pathname=='/')wallet();else if(location.pathname=='/requests')requestsPage();else if(location.pathname=='/split')splitPage();else if(location.pathname=='/authorizations')authorizationsPage();else location.href='/'}
async function wallet(){app.innerHTML='<div class="grid"><div class="stack"><section class="card" id="balance-card"></section><section class="card"><h2>Pay someone</h2><form id="pay-form">'+field('pay-handle','Handle')+field('pay-amount','Amount')+field('pay-note','Note')+'<label>Visibility<select data-testid="pay-visibility"><option value="public">Public</option><option value="private">Private</option></select></label><button data-testid="pay-submit">Send payment</button><div id="pay-msg"></div></form></section><section class="card"><h2>Request money</h2><form id="request-form">'+field('request-handle','Payer handle')+field('request-amount','Amount')+field('request-note','Note')+'<button data-testid="request-submit">Send request</button><div id="request-msg"></div></form></section><section class="card"><h2>Authorise funds</h2><form id="authorize-form">'+field('authorize-handle','Recipient handle')+field('authorize-amount','Amount')+field('authorize-note','Note')+'<label>Visibility<select data-testid="authorize-visibility"><option value="public">Public</option><option value="private">Private</option></select></label><button data-testid="authorize-submit">Place hold</button><div id="authorize-msg"></div></form></section></div><section class="card"><div class="row"><h2>Activity</h2><button class="secondary" data-testid="wallet-refresh" style="width:auto">Refresh</button></div><div id="activity"></div></section></div>';$('#wallet-refresh').onclick=refreshWallet;bindIdemForm('pay-form','payments','pay','pay-msg',()=>({to_handle:$('[data-testid=pay-handle]').value,amount:minor($('[data-testid=pay-amount]').value),note:$('[data-testid=pay-note]').value,visibility:$('[data-testid=pay-visibility]').value}),true);bindIdemForm('request-form','requests','request','request-msg',()=>({payer_handle:$('[data-testid=request-handle]').value,amount:minor($('[data-testid=request-amount]').value),note:$('[data-testid=request-note]').value}));bindIdemForm('authorize-form','authorizations','authorize','authorize-msg',()=>({to_handle:$('[data-testid=authorize-handle]').value,amount:minor($('[data-testid=authorize-amount]').value),note:$('[data-testid=authorize-note]').value,visibility:$('[data-testid=authorize-visibility]').value}));refreshWallet()}
function bindIdemForm(form,path,prefix,msgId,bodyFn,uncertain=false){let pending=null;$('#'+form).onsubmit=async e=>{e.preventDefault();let body;try{body=bodyFn()}catch(err){$('#'+msgId).innerHTML=errorBox(prefix+'-error',err.message);return}let signature=JSON.stringify(body);if(!pending||pending.signature!==signature)pending={signature,key:uid(),body};$('#'+msgId).innerHTML='';try{await api('/'+path,{method:'POST',headers:{'Idempotency-Key':pending.key},body:JSON.stringify(pending.body)});await refreshWallet()}catch(err){if(!err.status&&uncertain){$('#'+msgId).innerHTML='<div class="uncertain" data-testid="pay-uncertain">Outcome unknown. Retry to safely confirm.</div>'}else{$('#'+msgId).innerHTML=errorBox(prefix+'-error',err.message);await refreshWallet()}}}}
async function refreshWallet(){let version=++refreshVersion;try{let [m,a]=await Promise.all([api('/me'),api('/activity')]);if(version!==refreshVersion)return;me=m;showIdentity();$('#balance-card').innerHTML='<p class="eyebrow">Available to spend</p><div class="money" data-testid="wallet-available" data-amount="'+m.available+'">'+fmt(m.available)+'</div><div class="secondary-money"><span>Total <b data-testid="wallet-balance" data-amount="'+m.total+'">'+fmt(m.total)+'</b></span>'+(m.held?'<span>Held <b data-testid="wallet-held" data-amount="'+m.held+'">'+fmt(m.held)+'</b></span>':'')+'</div>';let box=$('#activity');if(!box)return;if(!a.payments.length)box.innerHTML='<p class="empty" data-testid="empty-activity">No activity yet.</p>';else box.innerHTML='<div data-testid="activity-list">'+a.payments.map(p=>'<article class="item" data-testid="activity-item-'+p.payment_id+'" data-visibility="'+p.visibility+'"><div class="row"><b data-testid="activity-parties-'+p.payment_id+'">@'+esc(p.from_handle)+' → @'+esc(p.to_handle)+'</b><b data-testid="activity-amount-'+p.payment_id+'">'+fmt(p.amount)+'</b></div><div data-testid="activity-note-'+p.payment_id+'">'+esc(p.note)+'</div><small class="muted">'+new Date(p.created_at).toLocaleString()+' · '+p.visibility+'</small></article>').join('')+'</div>'}catch(e){let card=$('#balance-card');if(card)card.innerHTML=errorBox('pay-error',e.message)}}
async function requestsPage(){app.innerHTML='<h1>Requests</h1><div id="request-page-msg"></div><div class="grid"><section class="card"><h2>Incoming</h2><div data-testid="incoming-list" id="incoming"></div></section><section class="card"><h2>Outgoing</h2><div data-testid="outgoing-list" id="outgoing"></div></section></div>';await refreshRequests()}
async function refreshRequests(){try{let x=await api('/requests');let incoming=x.requests.filter(q=>q.payer_id==me.user_id),outgoing=x.requests.filter(q=>q.requester_id==me.user_id);if(!x.requests.length){$('#incoming').innerHTML='<p data-testid="empty-requests" class="empty">No requests.</p>';$('#outgoing').innerHTML='';return}let render=(q,inc)=>'<article class="item" data-testid="request-item-'+q.request_id+'" data-status="'+q.status+'"><div class="row"><b>@'+esc(inc?q.requester_handle:q.payer_handle)+'</b><b data-testid="request-amount-'+q.request_id+'">'+fmt(q.amount)+'</b></div><p>'+esc(q.note)+'</p>'+(q.status=='pending'?'<div class="actions">'+(inc?'<button data-action="pay" data-id="'+q.request_id+'" data-testid="request-pay-'+q.request_id+'">Pay</button><button class="secondary" data-action="decline" data-id="'+q.request_id+'" data-testid="request-decline-'+q.request_id+'">Decline</button>':'<button class="danger" data-action="cancel" data-id="'+q.request_id+'" data-testid="request-cancel-'+q.request_id+'">Cancel</button>')+'</div>':'<span class="pill">'+q.status+'</span>')+'</article>';$('#incoming').innerHTML=incoming.map(q=>render(q,true)).join('');$('#outgoing').innerHTML=outgoing.map(q=>render(q,false)).join('');document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>requestAction(b.dataset.id,b.dataset.action))}catch(e){$('#request-page-msg').innerHTML=errorBox('request-error',e.message)}}
async function requestAction(id,action){try{let opt={method:'POST',body:'{}'};if(action=='pay')opt.headers={'Idempotency-Key':uid()};await api('/requests/'+id+'/'+action,opt);$('#request-page-msg').innerHTML='';await refreshRequests()}catch(e){$('#request-page-msg').innerHTML=errorBox('request-error',e.message);await refreshRequests()}}
function splitPage(){app.innerHTML='<section class="card" style="max-width:680px;margin:auto"><p class="eyebrow">Share fairly</p><h1>Split a bill</h1><form id="split-form">'+field('split-amount','Total amount')+field('split-handles','Handles, separated by commas')+field('split-note','Note')+'<div data-testid="split-preview" id="split-preview" class="card"></div><button data-testid="split-submit">Create requests</button><div id="split-msg"></div></form></section>';let update=()=>{try{let total=minor($('[data-testid=split-amount]').value),hs=$('[data-testid=split-handles]').value.split(',').map(x=>x.trim()).filter(Boolean);if(!hs.length)throw Error('Add at least one handle');let base=Math.floor(total/hs.length),extra=total%hs.length;$('#split-preview').innerHTML=hs.map((h,i)=>'<div class="row"><span>@'+esc(h)+'</span><b data-testid="split-share-'+h+'">'+fmt(base+(i<extra?1:0))+'</b></div>').join('')}catch{$('#split-preview').innerHTML='<span class="muted">Enter an amount and participants to preview shares.</span>'}};$('[data-testid=split-amount]').oninput=update;$('[data-testid=split-handles]').oninput=update;bindIdemForm('split-form','splits','split','split-msg',()=>({amount:minor($('[data-testid=split-amount]').value),participant_handles:$('[data-testid=split-handles]').value.split(',').map(x=>x.trim()).filter(Boolean),note:$('[data-testid=split-note]').value}))}
async function authorizationsPage(){app.innerHTML='<h1>Authorisations</h1><div id="authorization-page-msg"></div><section class="card"><div id="authorization-list"></div></section>';await refreshAuthorizations()}
async function refreshAuthorizations(){try{let x=await api('/authorizations'),box=$('#authorization-list');if(!x.authorizations.length){box.innerHTML='<p class="empty" data-testid="empty-authorizations">No authorisations.</p>';return}box.innerHTML='<div data-testid="authorization-list">'+x.authorizations.map(a=>{let incoming=a.to_user_id==me.user_id,open=a.status=='open';return '<article class="item" data-testid="authorization-item-'+a.authorization_id+'" data-status="'+a.status+'"><div class="row"><div><b>@'+esc(a.from_handle)+' → @'+esc(a.to_handle)+'</b><div class="muted">'+esc(a.note)+'</div></div><b data-testid="authorization-amount-'+a.authorization_id+'">'+fmt(a.amount)+'</b></div>'+(a.status=='captured'?'<p>Captured <b data-testid="authorization-captured-'+a.authorization_id+'">'+fmt(a.captured_amount)+'</b></p>':'')+'<small data-testid="authorization-expires-'+a.authorization_id+'">'+a.expires_at+'</small>'+(open?'<div class="actions" style="margin-top:12px">'+(incoming?'<input aria-label="Capture amount" data-testid="authorization-capture-amount-'+a.authorization_id+'" value="'+decimal(a.remaining_amount)+'"><button data-capture="'+a.authorization_id+'" data-testid="authorization-capture-'+a.authorization_id+'">Capture</button>':'<button class="danger" data-void="'+a.authorization_id+'" data-testid="authorization-void-'+a.authorization_id+'">Void</button>')+'</div>':' <span class="pill">'+a.status+'</span>')+'</article>'}).join('')+'</div>';document.querySelectorAll('[data-capture]').forEach(b=>b.onclick=()=>authAction(b.dataset.capture,'capture'));document.querySelectorAll('[data-void]').forEach(b=>b.onclick=()=>authAction(b.dataset.void,'void'))}catch(e){$('#authorization-page-msg').innerHTML=errorBox('authorization-error',e.message)}}
function decimal(n){let p=me.minor_units;if(!p)return String(n);let v=String(n).padStart(p+1,'0');return v.slice(0,-p)+'.'+v.slice(-p)}
async function authAction(id,action){try{let opt={method:'POST',body:'{}'};if(action=='capture'){opt.body=JSON.stringify({amount:minor($('[data-testid=authorization-capture-amount-'+id+']').value)});opt.headers={'Idempotency-Key':uid()}}await api('/authorizations/'+id+'/'+action,opt);$('#authorization-page-msg').innerHTML='';await refreshAuthorizations()}catch(e){$('#authorization-page-msg').innerHTML=errorBox('authorization-error',e.message);await refreshAuthorizations()}}
$('[data-testid=logout-button]').onclick=()=>{localStorage.removeItem('pocketfulToken');location.href='/login'};boot();
</script></body></html>`
